### ISSUE TITLE
Doesnt prepend "http://" to urls that just start with "www.*"

### ISSUE THREAD

**Issue by omasback** [scottcorgan/angular-linkify#11]
at least a "//" or "#" is needed for hrefs to work

**Comment by nikhilvm1993** [comment]
@elado I have images in my html code.So the image links also wrapped with <a href="">

**Comment by addula** [comment]
@scottcorgan When is this issue going to be resolved? I am using linkify and stuck with http/https issue in anchors.

**Comment by addula** [comment]
@scottcorgan I am trying to submit PR but not able to do it as permission denied. Please provide permission so that I can submit PR on this issue.

**Comment by addula** [comment]
Raised PR with proposed changes. https://github.com/scottcorgan/angular-linkify/pull/27

**Comment by addula** [comment]
@scottcorgan Thank you
